### ISSUE TITLE
 geocode.py usage example not correct

### ISSUE THREAD

**Issue by falkamelung** [insarlab/PySAR#56]
Not a bit deal, but there is some confusion with the geocode usage example.`geocode.py --help` prints out at the end:
```
example:
  geocode.py velocity.h5
  geocode.py velocity.h5 -b -0.5 -0.25 -91.3 -91.1
  geocode.py velocity.h5 timeseries.h5 -t pysarApp_template.txt -o ./GEOCODE --update
```
Although the `-o` says this is the option for a file. the user expects that
`geocode.py velocity.h5 timeseries.h5 -t pysarApp_template.txt -o ./GEOCODE —update`
will write into the GEOCODE directory (as pysarApp  does this). This is a confusion but not really a bug. 

`geocode.py velocity.h5 -t pysarApp_template.txt -o qqq --update` works as expected, however with two arguments the `qqq` is ignored and I get `geo_velocity.h5` and `geo_timeseries.h5`

**Comment by yunjunz** [comment]
--outdir is for output directory, -o / --output is for output file name. The confusion in help is fixed now. Thank you for pointing it out @falkamelung.
